name: Release APK

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  release:
    if: github.actor == 'Mupceet' && github.ref == 'refs/heads/md3/port/eink'
    uses: ./.github/workflows/auto-release.yml
    with:
      publish: true
    secrets: inherit
